Repository OnBoarding-Park-is-best/week4-flower, pull requests merged in 2022-02, with the labels that each got.

#7 Feat: FlowerClass 컴포넌트 구현
  index.html
  package.json
  src/App.js
  src/assets/img_handtied.jpg
  src/assets/img_homeclass.jpeg
  src/assets/img_oasis.jpg
  src/constants/classData.js
  src/modules/FlowerClass/FlowerClass.js
  src/modules/FlowerClass/FlowerClass.module.css
  webpack.config.js
  yarn.lock
Labels: Feature, 리뷰 요청

#5 :sparkles: feat: GNB 컴포넌트 구현
  index.html
  src/App.js
  src/assets/icon_cart.png
  src/assets/icon_person.png
  src/assets/logo_column.png
  src/assets/logo_row.png
  src/global.module.css
  src/modules/FlowerClass/FlowerClass.module.css
  src/modules/GNB/GNB.js
  src/modules/GNB/GNB.module.css
  src/utils/height.js
  webpack.config.js
Labels: Feature, 리뷰 요청

#11 ✨ feat: Footer 컴포넌트 구현
  src/App.js
  src/assets/images/facebook.png
  src/assets/images/instagram.png
  src/assets/images/logo_footer.png
  src/assets/images/youtube.png
  src/modules/Footer/Footer.js
  src/modules/Footer/Footer.module.css
Labels: 리뷰 요청

#6 :sparkles: feat: Movie 컴포넌트 구현
  src/App.js
  src/modules/GNB/GNB.js
  src/modules/Movie/Movie.js
  src/modules/Movie/Movie.module.css
Labels: Feature, 리뷰 요청

#13 :sparkles: GNB 버튼 onClick 동작 구현
  src/constants/id.js
  src/modules/FlowerClass/FlowerClass.js
  src/modules/GNB/GNB.js
  src/modules/Movie/Movie.js
  src/modules/Movie/Movie.module.css
Labels: Feature, Refactor, 리뷰 요청

#14 ✨ feat: Popup 컴포넌트 구현
  src/App.js
  src/assets/icon_close.png
  src/assets/img_popup.jpeg
  src/modules/Popup/Popup.js
  src/modules/Popup/Popup.module.css
Labels: Feature

#16 :bug: fix: 너비 조절 문제로 가로 스크롤 생기는 현상 해결
  src/modules/FlowerClass/FlowerClass.module.css
Labels: Refactor

#10 ✨ feat: Banner 컴포넌트 구현
  index.html
  src/App.js
  src/constants/bannerData.js
  src/modules/Banner/Banner.js
  src/modules/Banner/Banner.module.css
Labels: Feature

#18 ♻️ refactor: Banner 컴포넌트 리팩토링
  src/constants/bannerData.js
  src/modules/Banner/Banner.js
  src/modules/Banner/Banner.module.css
  src/utils/string.js
Labels: Refactor
